// <auto-generated />
using System;
using Compras.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Compras.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Compras.Domain.Entities.CompraCab", b =>
                {
                    b.Property<int>("IdCompraCab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_CompraCab");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompraCab"));

                    b.Property<DateTime>("FecRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("FecRegistro");

                    b.Property<decimal>("Igv")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Igv");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SubTotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("IdCompraCab");

                    b.ToTable("CompraCab", (string)null);
                });

            modelBuilder.Entity("Compras.Domain.Entities.CompraDet", b =>
                {
                    b.Property<int>("IdCompraDet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_CompraDet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompraDet"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<int>("IdCompraCab")
                        .HasColumnType("int")
                        .HasColumnName("Id_CompraCab");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("Id_producto");

                    b.Property<decimal>("Igv")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Igv");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Precio");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Sub_Total");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("IdCompraDet");

                    b.HasIndex("IdCompraCab");

                    b.ToTable("CompraDet", (string)null);
                });

            modelBuilder.Entity("Compras.Domain.Entities.CompraDet", b =>
                {
                    b.HasOne("Compras.Domain.Entities.CompraCab", "CompraCab")
                        .WithMany("Detalles")
                        .HasForeignKey("IdCompraCab")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompraCab");
                });

            modelBuilder.Entity("Compras.Domain.Entities.CompraCab", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
