// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ventas.Infrastructure.Persistence;

#nullable disable

namespace Ventas.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ventas.Domain.Entities.VentaCab", b =>
                {
                    b.Property<int>("IdVentaCab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_VentaCab");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVentaCab"));

                    b.Property<DateTime>("FecRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecRegistro");

                    b.Property<decimal>("Igv")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Igv");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SubTotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("IdVentaCab");

                    b.ToTable("VentaCab", (string)null);
                });

            modelBuilder.Entity("Ventas.Domain.Entities.VentaDet", b =>
                {
                    b.Property<int>("IdVentaDet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_VentaDet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVentaDet"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("Id_producto");

                    b.Property<int>("IdVentaCab")
                        .HasColumnType("int")
                        .HasColumnName("Id_VentaCab");

                    b.Property<decimal>("Igv")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Igv");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Precio");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Sub_Total");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("IdVentaDet");

                    b.HasIndex("IdVentaCab");

                    b.ToTable("VentaDet", (string)null);
                });

            modelBuilder.Entity("Ventas.Domain.Entities.VentaDet", b =>
                {
                    b.HasOne("Ventas.Domain.Entities.VentaCab", "VentaCab")
                        .WithMany("Detalles")
                        .HasForeignKey("IdVentaCab")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VentaCab");
                });

            modelBuilder.Entity("Ventas.Domain.Entities.VentaCab", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
