// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movimientos.Infrastructure.Persistence;

#nullable disable

namespace Movimientos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609233858_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Movimientos.Domain.Entities.MovimientoCab", b =>
                {
                    b.Property<int>("IdMovimientoCab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_MovimientoCab");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimientoCab"));

                    b.Property<DateTime>("FecRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fec_registro");

                    b.Property<int>("IdDocumentoOrigen")
                        .HasColumnType("int")
                        .HasColumnName("Id_DocumentoOrigen");

                    b.Property<int>("IdTipoMovimiento")
                        .HasColumnType("int")
                        .HasColumnName("Id_TipoMovimiento");

                    b.HasKey("IdMovimientoCab");

                    b.ToTable("MovimientoCab", (string)null);
                });

            modelBuilder.Entity("Movimientos.Domain.Entities.MovimientoDet", b =>
                {
                    b.Property<int>("IdMovimientoDet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_MovimientoDet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimientoDet"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<int>("IdMovimientoCab")
                        .HasColumnType("int")
                        .HasColumnName("Id_movimientocab");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("Id_Producto");

                    b.HasKey("IdMovimientoDet");

                    b.HasIndex("IdMovimientoCab");

                    b.ToTable("MovimientoDet", (string)null);
                });

            modelBuilder.Entity("Movimientos.Domain.Entities.MovimientoDet", b =>
                {
                    b.HasOne("Movimientos.Domain.Entities.MovimientoCab", "MovimientoCab")
                        .WithMany("Detalles")
                        .HasForeignKey("IdMovimientoCab")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovimientoCab");
                });

            modelBuilder.Entity("Movimientos.Domain.Entities.MovimientoCab", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
